#' use EnsDb to generate an exon-level model of genes identified by symbol
#' @importFrom GenomicFeatures exons
#' @importFrom AnnotationFilter SymbolFilter
#' @param sym a character() vector of gene symbols
#' @param resource should be or inherit from EnsDb, 
#' answering exons(), with AnnotationFilter::SymbolFilter 
#' as filter parameter
#' @param columnsKept character vector used as `columns` param in exons()
#' @param \dots passed to exons()
#' @return data.frame instance with exons in rows
#' @examples
#' if (requireNamespace("EnsDb.Hsapiens.v75")) {
#'  orm = genemodelDF("ORMDL3", EnsDb.Hsapiens.v75::EnsDb.Hsapiens.v75)
#'  dim(orm)
#' }
#' head(orm)
#' @export
genemodelDF = function(sym, resource, 
      columnsKept=c("gene_id", "tx_id"), ...) {
  if (!is(resource, "EnsDb")) warning("resource not of class EnsDb")
  exs = exons(resource, filter=SymbolFilter(sym), 
         columns=columnsKept, ...)
  names(exs) = NULL
  as(exs, "data.frame")
}

#' create a GeneRegionTrack instance for selected symbols
#' @param sym character vector of gene symbols, should be neighboring genes
#' @param id_elem vector of names of columns generated by genemodelDF to be
#' used to label transcripts
#' @importFrom Gviz GeneRegionTrack
#' @param resource should be or inherit from EnsDb, 
#' answering exons(), with AnnotationFilter::SymbolFilter 
#' as filter parameter
#' @param \dots passed to genemodelDF
#' @examples
#' if (requireNamespace("EnsDb.Hsapiens.v75") &
#'     requireNamespace("Gviz")) {
#'  orm = genemodForGviz("ORMDL3", resource= EnsDb.Hsapiens.v75::EnsDb.Hsapiens.v75)
#'  orm
#'  Gviz::plotTracks(orm, showId=TRUE) # change id_elem for shorter id string
#' }
#' @export
genemodForGviz = function(sym="ORMDL3", id_elem=c("symbol", "tx_id"),
        resource = EnsDb.Hsapiens.v75::EnsDb.Hsapiens.v75, ...) {
 exdf = genemodelDF(sym=sym, resource=resource, ...)
 cind = which(names(exdf)=="seqnames")
 if (length(cind)==1) names(exdf)[cind] = "chromosome"
 GeneRegionTrack(exdf, transcript=exdf$tx_id, 
     symbol = apply(exdf[,id_elem,drop=FALSE],1, paste, collapse=" "), ...)
}
